# 数据库连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    decryptFlag: false
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.25.137:3306/hyx_db?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: hyx_adm
    password: hyx_adm
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 10
    maxActive: 50
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x' from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 100
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
#线程池配置
thread:
  corePoolSize: 20
  maxPoolSize: 30
  queueCapacity: 500
  
  
  