# 数据库连接池配置
spring:
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      decryptFlag: false
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://114.67.96.200:3306/demo?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: hyxadm
      password: hyxadm
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 10
      maxActive: 50
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
#dubbo配置
dubbo: 
   application: 
      name: dubbo-application-core
   protocol: 
      name: dubbo
      port: 20880
   registry: 
      address: zookeeper://114.67.96.200:2181
   packageName: com.hyx.demo.core.dubbo.providers
      
  
  